### ISSUE TITLE
route('produits.show' , $ordinateur)  au lieu de  route('produits.show' , $tablette) 

### ISSUE THREAD

**Issue by SamuelHKonan** [daviidy/whatprice#1]
ErrorException (E_ERROR)
Variable non définie: tablette (Affichage: /var/www/vhosts/apprendre-lelevage.ci/whatprice.rikudotech.com/resources/views/produits/ordinateurs.blade.php)

   <div class = "probootstrap-card-text" > 
              <h2 class = "probootstrap-carte-rubrique" > <a href=" <? php echo e (route ('produits.show', $tablette )); ?>

**Comment by daviidy** [comment]
Ok je règle ca

**Comment by daviidy** [comment]
bug fixed
vous pouvez voir le resultat ici: http://whatprice.rikudotech.com/ordinateurs
